#!/bin/sh
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev 2>/dev/null || true
export PATH=/bin:/sbin:/usr/bin:/usr/sbin
echo ""
echo "=== QEMU ARM64 Embedded Linux ==="
echo "Kernel: $(uname -r)"
echo ""
# setsid: yeni oturum (session) acar
# cttyhack: /dev/console u controlling terminal olarak atar
exec setsid cttyhack /bin/sh
